apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: surfersapi
  labels:
    apps.tanzu.vmware.com/workload-type: web
    deployment-model: blue-green
    app.kubernetes.io/part-of: surferslookout
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/language: python
    apis.apps.tanzu.vmware.com/register-api: "true"
    component: backend
spec:
  params:
  - name: clusterBuilder
    value: full-jammy
  - name: annotations
    value:
      autoscaling.knative.dev/min-scale: "1"
      autoscaling.knative.dev/max-scale: "50"
      autoscaling.knative.dev/scale-down-delay: "2s"
      autoscaling.knative.dev/initial-scale: "1"
      autoscaling.knative.dev/window: "10s"
      autoscaling.knative.dev/target: "40"
      autoscaling.knative.dev/metric: "rps"
      autoscaling.knative.dev/target: "50"
  - name: api_descriptor
    value:
      type: openapi
      location:
        #baseURL: "http://surfersapi.default"      # Added baseURL to prevent the resolvedURL pointing to the SSL url
        path: "/api/v1/api-docs"
      owner: group:surfers-crew
      system: surferslookout
      description: "Surferslookout forecast api"
  - name: git_user_email
    value: davidlloyd0@gmail.com
  - name: git_user_name
    value: davlloyd
  source:
    git:
      url: https://github.com/davlloyd/surfers-api
      ref:
        branch: main
